language: node_js
node_js:
- 10  
before_install:
- npm install -g npm
script:
- npm install
- npm run test-headless
deploy:
  provider: heroku
  api_key: 
    secure: 3d1959c4-9d87-448c-bd6f-79ff189b6079
  app: client-turing-ecommerce
  on:
    repo: tksilicon/client-turing-ecommerce
  