language: node_js
node_js:
- 10  
before_install:
- npm install -g npm
script:
- npm install
- npm run test-headless
deploy:
  provider: heroku
  api_key: 
    secure: K0ssPcciLNqJRhjqx9vq+kJQ1wWN/73QGrenVv75ibnWVCTohKsi37MQs7yEamNC4/JZjCMalQSzINyDLcHAs7MyPOKEHEGGHQaa0uTjhlXsnfx8zFj0W2rctiZbWck986LeC4cJjiKvGyiKLRmrkg4JAmfvCVMK/llFgiB/cjjGjWeJzNMOtAjLTnzoLYycX2Rfh3E61Jps0Ii+1iryXSUIZW4bbgUb05fUfYZwPlIxRA+5tN+/e2muLroTIg+FsKn7sAW+sSK2fvCEFILNx89V8ZBuAvPnOEhqF/DkfStQezNVXClm+x4nmzwGCY2PE+ZtOEI8KUI2wKAAzhtEHu4t84YPwGqmc8OyJzw26AOqbeRFJu8CIx/+bTvkV4h/u3Mu2nkFtX3S6ER0paeBawospuieOttTCKDyoY49XdS35bZVjSuQoAWuoTCJKzLXw5+taDGtg1UTn4rfnHdqMOQkF3lJsTo251eEvdSwFuty88+zqPFTt3/pxQAOxcQcR1M6ydfuiHMWNGqxbjphUbS3ryM9HNbDHwZIwAY597+WOMy44HdXjWt+D/fQl+Ye1y+yji/sJXVaOgOCwBe8fzzVMwFViCAV6oVWrQ/5bOwFVR2qVuAMa7Xy5EBNoeLlsYRDiL5WPScfisNmjw6e136IKbysPSEZjtrW0oHyt0s=
  app: client-turing-ecommerce
  on:
    repo: tksilicon/client-turing-ecommerce
  