language: node_js
node_js:
- 10  
before_install:
- npm install -g npm
script:
- npm install
- npm run test-headless
deploy:
  provider: heroku
  api_key: 
    secure: "secure api key" 
  app: client-turing-ecommerce
  on:
    repo: tksilicon/client-turing-ecommerce
  